### PR TITLE
pipe source: create-dir() workaround

### PR DESCRIPTION
**Pull request by zsoltgyulai94**
Added note about possible failure and workaround for pipe sources.

### CODE REVIEW

**Comment by czanik** [comment]
I'd rather add it to https://github.com/syslog-ng/syslog-ng.github.io/tree/a452ee2e51b374c5606ab4c04928b38400e278d7/doc/_admin-guide/060_Sources/110_Pipe as it is more generic information than just the create-dir() option. The reader might not reach this point of the documentation when in panic :-)

**Comment by zsoltgyulai94** [comment]
Included the note there as well. I think it's good to have it in both places.

**Review by czanik — APPROVED** [review]
Thanks, looks good to me.

**Review by mrgarris0n — APPROVED** [review]
Approved, but please consider creating a snippet for duplicated content.

**Pull request merged**
